### ISSUE TITLE
Pagination Problems

### ISSUE THREAD

**Issue by 0xdade** [pierce403/nweb#11]
The next page button is available and tries to iterate pages regardless of how many results showed up in a search query. The next page button should only show up when the result count is higher than the pagination count. 

There is no "previous page" button once we've moved beyond the first page.

There is no "next page" button when just browsing instead of using a search query.

**Comment by tophertimzen** [comment]
Fixed with https://github.com/pierce403/nweb/commit/f9bcd57946faa75c30399a89079c5f87e80c5008
