### ISSUE TITLE
getheadshot should not be called on each scan

### ISSUE THREAD

**Issue by tophertimzen** [pierce403/nweb#14]
`getheadshot` is currently called every time a scan finishes in `nweb_agent.py` even if the ports returned will have no headshot data. Known ports such as `80`, `443`, `5900`, among others, will have headshots but others won't. It would be better to maintain a list of ports worth trying to headshot before entering `getheadshot` as `getheadshot` will result in a 2 minute timeout if nothing is present which vastly reduces the speed of scans.

**Comment by 0xdade** [comment]
Fixed in merge from 0xdade/nweb 7e2ebc73641d31fc717a279df9e317fcecbe5cb9.

Recommend closing.
